name: Monitor Issues

on:
  workflow_call:
    inputs:
      operations-per-run:
        description: 'Number of operations per run'
        required: false
        default: '30'
    secrets:
      repo-token:
        description: 'GitHub token used to authenticate and modify issues'
        required: true

jobs:
  monitor-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v9
        with:
          exempt-issue-labels: 'feature request,question'
          days-before-issue-stale: 0
          days-before-issue-close: 0
          stale-issue-label: "stale"
          stale-issue-message: "This issue has been marked as stale due to 6 months of inactivity. As part of our effort to address every issue properly, please feel free to remove the stale label or keep this issue active by leaving a comment. Otherwise, it will be closed in 7 days"
          close-issue-message: "This issue was closed due to 7 days of inactivity after being marked as stale. Feel free to reopen it if it remains relevant."
          days-before-pr-close: false
          days-before-pr-stale: false
          ascending: true
          operations-per-run: ${{ inputs.operations-per-run }}
          repo-token: ${{ secrets.repo-token }}
