name: Test Monitor Issues

on:
  workflow_dispatch:
    inputs:
      operations-per-run:
        description: 'Number of operations per run'
        required: false
        default: '30'
  schedule:
    - cron: "0 0 * * *"  # Runs once a day at midnight

jobs:
  workflow_call_1:
    uses: reshmifrog/.github/actions/monitor-issues@feature/monitor-issues-reusable
    with:
      repo-token: ${{ secrets.REPO_TOKEN }}
      operations-per-run: 30
